### ISSUE TITLE
SNAPSHOT version dance?

### ISSUE THREAD

**Issue by bhamail** [bbottema-circleci/circleci-orbs#6]
I have seen a few folks get confused by the current behavior of version updating. For example, given an initial version of 0.0.1: Currently, when a (patch) deploy is performed, the version is nicely updated (to 0.0.2), then the project is deployed with the new version (0.0.2), and that version (0.0.2) is committed. Great!

However, the "end state" is the "just deployed" version (0.0.2) is now what people see in the source code. This is a little confusing, as while they are working on the code, they see v0.0.2, but that version has already left the building. The next version that would be deployed (e.g. the code they are actually working on) is actually for v0.0.3.

So....I was wondering if you had thoughts about how to make the "end state" show something like 0.0.3-SNAPSHOT. When it is time to deploy "version next", the ORB would deploy 0.0.3 (non-snapshot), commit that version (with no-ci), then update the version again to 0.0.4-SNAPSHOT and commit it (with no-ci). This is pretty much what the maven release plugin does.

The above dance adds a number of steps to the routine, but I like the benefit of having a clear "SNAPSHOT" version suffix in the source tree while development is ongoing.

Thoughts? Solutions? Repulsions? :)

**Comment by bbottema** [comment]
~~I'm all for it! Actually, I used to work like that, but I was just glad this thing worked and since I could work with it I was happy. Still, handling it like the release plugin would be the better way.~~

**Comment by bbottema** [comment]
Actually I just remembered why ended up with the current way of working. The reason is because you only know the real release version when you click in the pipeline after the build started. I'll try to explain.

Let's assume the last released version is 1.0.0.

After releasing 1.0.0, to set a SNAPSHOT, the Orb script would need to estimate the next version, right. Now let's assume we'll take the minimum increase, a patch version increase, the Orb script sets the current version to 1.0.1-SNAPSHOT. Now what is the Orb script supposed to do with the next release? Revert the patch version increase (back to 1.0.0) and then apply the required increase as clicked in the pipeline (say a minor release at 1.1.0)?

This is getting rather hairy and I wanted to keep the script straightforward.

**Comment by bhamail** [comment]
I was thinking it would only be necessary to add a "new" commit step to the end of the existing process.
After the current logic of:

```
...
            echo "Pushing new version and tag..."
            git commit -am "released ${MVN_VERSION} [skip ci]"
            git tag -a ${MVN_VERSION} -m "Release ${MVN_VERSION}"
            ssh-agent sh -c 'ssh-add ~/.ssh/id_rsa; git push $CIRCLE_REPOSITORY_URL'
            ssh-agent sh -c 'ssh-add ~/.ssh/id_rsa; git push origin --tags'
            echo "Successfully released ${MVN_VERSION}"
```
then a second commit would be done (w/ [skip ci]) to bump the version, e.g.

```
            psudeocodeTo_patch-internal_versioncommand-withSNAPSHOT_suffix
            MVN_VERSION_SNAPSHOT=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
            echo "Committing next development version ${MVN_VERSION_SNAPSHOT}..."
            git commit -am "next development version ${MVN_VERSION_SNAPSHOT} [skip ci]"
            ssh-agent sh -c 'ssh-add ~/.ssh/id_rsa; git push $CIRCLE_REPOSITORY_URL'
```

**Comment by bbottema** [comment]
> then a second commit would be done (w/ [skip ci]) to bump the version, e.g.

So this is where it gets hairy; you bump the version, even though you don't know whether the next version is going to be a patch, minor or major. Then to actually perform the right release next time, you need to revert this bump in order to perform the correct bump.

**Comment by bhamail** [comment]
I was thinking to keep it simple by always making the next dev version a "patch" increment. If the user wants to do "larger" increments, they can do that themselves (outside the ORB).

**Comment by bbottema** [comment]
Then you have two release management workflows.. not exactly what I would call keeping it simple :smile:

The novelty about this Orb _is_ that you can select the release version from the pipeline.

**Comment by bhamail** [comment]
I see your point. 

I'm also toying with the idea of an ORB that would leverage the maven-release-plugin. If I could keep the ORB complexity manageable, using m-relase-p would avoid reinventing much of the release plugin logic...a big if.

Separately, Have you noticed "Failed" badges on projects using your ORB? I'm not sure if somehow the un-run workflows ("patch, minor, major") could be contributing to "stale" status badge.

**Comment by bbottema** [comment]
> Separately, Have you noticed "Failed" badges on projects using your ORB? I'm not sure if somehow the un-run workflows ("patch, minor, major") could be contributing to "stale" status badge.

Yeah that is a little annoying. On the other hand, I stopped showing that badge on my project pages altogether, as it is completely unrelated to the released version and thus the current API. It's a gimmick more than anything, I feel.

**Comment by bhamail** [comment]
I had another idea: What about a user configurable set of optional "post-deploy" steps? By default the "post-deploy" steps would be an empty set of steps. Like the [after-deps](https://circleci.com/docs/2.0/reusing-config/#steps) example.  

I'm thinking I could add step(s) to increment the version and commit/push that change in such a "post-deploy" set of steps.

**Comment by bbottema** [comment]
That's pretty good in general, actually. What about a variable that you can set to true for adding a SNAPSHOT specifically?

**Comment by bhamail** [comment]
> ... What about a variable that you can set to true for adding a SNAPSHOT specifically?

That would be excellent too!
